Support AES decryption
49nord/zip pull request #2
Opened 2020-10-09 15:22 UTC by Lireer

2020-10-12 19:27 UTC, mbr requested changes
Mainly two objections:

* More docs - especially panics should be documented.
* Too much conditional stuff. Only code sections that pull in additional dependencies should be feature gated. Looking at the existing code, it will still parse metadata about BZip compression, even if the feature is deactivated!

2020-10-12 19:27 UTC, mbr commented on src/aes.rs
> +use crate::aes_ctr;
The module itself needs a (if brief) docstring.

2020-10-12 19:27 UTC, mbr commented on src/aes.rs
> +fn cipher_from_mode(aes_mode: AesMode, key: &[u8]) -> Box<dyn aes_ctr::AesCipher> {
Docstring here?

Potential panics should be mentioned.

2020-10-12 19:27 UTC, mbr commented on src/aes.rs
> +pub enum AesVendorVersion {
An explanation with reference to the spec could help here.

2020-10-12 19:27 UTC, mbr commented on src/aes.rs
> +#[cfg(feature = "aes-crypto")]
Was it not an option to feature gate the whole module, instead of having these sprinkled feature gates?

If it interferes too much with the case of unzipping non-encrypted archives we can leave as is.

2020-10-12 19:27 UTC, mbr commented on src/aes.rs
> +    pub fn validate(mut self, password: &[u8]) -> io::Result<Option<AesReaderValid<R>>> {
Should document return value here, as it is not immediately clear that `Ok(None)` is "all good, but wrong password".

2020-10-12 19:27 UTC, mbr commented on src/aes.rs
> +pub struct AesReaderValid<R: Read> {
Short note what this is, especially to be able to distinguish it from the `AesReader`.

2020-10-12 19:27 UTC, mbr commented on src/aes.rs
> +            if !constant_time_eq(computed_auth_code, &read_auth_code) {
I can't think of a scenario why we would need constant time comparison here. If not, we could rid of the dependency?

Assuming we hold the valid password, an attacker can supply any number of ZIP archives. Without constant time comparison, assume the attacker can perfectly guess either the authentication code (which they already have, since they are supplying it in the archive).

The other way around this would give them, at best, a way to have an oracle to get any bytes encrypted by us with the password.

Actually, that's bad, it might lead to key recovering if I am not mistaken. There are some safeguards, but leave the constant time in :)

2020-10-12 19:27 UTC, mbr commented on src/aes_ctr.rs
>      /// Creates a new zip variant AES-CTR key stream.
This needs panics documented (wrong key size?)

2020-10-12 19:27 UTC, mbr commented on src/aes_ctr.rs
> +pub trait AesCipher {
Docs required as well =)

2020-10-12 19:27 UTC, mbr commented on src/compression.rs
> +    AES,
This should be named `Aes` according to Rust naming guidelines. If the rest of the crate violates those though, we can leave as-is.

2020-10-12 19:27 UTC, mbr commented on src/crc32.rs
> +    ae2_encrypted: bool,
We can make this non-conditional and set it to `false` in these cases, it makes the code a little less sphaghetti-esque?

2020-10-12 19:27 UTC, mbr commented on src/crc32.rs
> +        #[cfg(feature = "aes-crypto")]
See above.

2020-10-12 19:27 UTC, mbr commented on src/read.rs
> +    #[cfg(feature = "aes-crypto")] aes_info: Option<(AesMode, AesVendorVersion)>,
To sum it up, all the aes metadata parsing can stay *in*, the overhead of having 2-4 extra bytes is perfectly fine. Only the parts that require additional dependencies should be feature gated!

2020-10-14 14:09 UTC, Lireer commented on src/aes.rs
> +#[cfg(feature = "aes-crypto")]
The new changes in fa75d18 that feature gating is only required when using make_reader and should now interfere less with the rest of the code.

2020-10-14 14:14 UTC, Lireer commented on src/aes.rs
> +            if !constant_time_eq(computed_auth_code, &read_auth_code) {
The [docs](https://docs.rs/crypto-mac/0.9.1/crypto_mac/struct.Output.html#method.into_bytes) for `into_bytes` of the crypto_mac crate suggest guarding against timing attacks.

Better safe than sorry :)

2020-10-19 16:25 UTC, mbr approved these changes
Nice work!

2020-10-19 16:25 UTC, merged